apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: my-apim
spec:
  wildcardDomain: apps.cluster-bkmnw.bkmnw.sandbox499.opentlc.com
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: false
  imagePullSecrets:
  - name: 6340056-mo-lab-1-pull-secret
  system:
    appSpec:
      replicas: 1
    sidekiqSpec:
      replicas: 1
    sphinxSpec: {}
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
  backend:
    cronSpec:
      replicas: 1
    listenerSpec:
      replicas: 1
    workerSpec:
      replicas: 1
  tenantName: 3scale
  apicast:
    managementAPI: status
    openSSLVerify: false
    productionSpec:
      replicas: 1
    responseCodes: true
    stagingSpec:
      replicas: 1
