apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: my-apim
spec:
  wildcardDomain: apps.cluster-bkmnw.bkmnw.sandbox499.opentlc.com
  resourceRequirementsEnabled: false
  imagePullSecrets:
  - name: 6340056-mo-lab-1-pull-secret
