apiVersion: maistra.io/v1
kind: ServiceMeshExtension
metadata:
  name: threescale-wasm-auth
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: productpage
  config:
    apiVersion: maistra.io/v1
    system:
      name: backend-listener
      upstream: https://backend-3scale.apps.cluster-bkmnw.bkmnw.sandbox499.opentlc.com
      token: 7e06685d5ca405aa675f5e328c470e38edc86d24d39b64d9ad0d064c9279b057
      ttl: 5000
  image: registry.redhat.io/openshift-service-mesh/3scale-auth-wasm-rhel8:0.0.1
  phase: PostAuthZ
  priority: 100