apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: system-entry
 namespace: bookinfo
spec:
 hosts:
   - system-provider.amp.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - name: http
     number: 3000
     protocol: HTTP
 resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: backend-entry
 namespace: bookinfo
spec:
 hosts:
   - backend-listener.amp.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - name: http
     number: 3000
     protocol: HTTP
 resolution: DNS
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: bookinfo-oidc
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: >-
      https://keycloak-sso.apps.cluster-bkmnw.bkmnw.sandbox499.opentlc.com/auth/realms/master
    jwksUri: >-
      https://keycloak-sso.apps.cluster-bkmnw.bkmnw.sandbox499.opentlc.com/auth/realms/master/protocol/openid-connect/certs
---
apiVersion: maistra.io/v1
kind: ServiceMeshExtension
metadata:
  name: threescale-wasm-auth
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: productpage
  image: registry.redhat.io/openshift-service-mesh/3scale-auth-wasm-rhel8:0.0.1
  phase: PostAuthZ
  priority: 100
  config:
    api: v1
    system:
      name: system
      token: aa50e73eef893e401cbbe89c4c23c554cf46acfe0432214bef5e5f2e66b953ca
      upstream:
        name: >-
          outbound|3000||system-provider.amp.svc.cluster.local
        timeout: 5000
        url: 'http://system-provider.amp.svc.cluster.local'
    backend:
      extensions:
      - no_body
      name: backend
      upstream:
        name: >-
          outbound|3000||backend-listener.amp.svc.cluster.local
        timeout: 5000
        url: 'http://backend-listener.amp.svc.cluster.local'
    services:
    - id: '3'
      token: 22214358bf38370f03e305ea1f986106e752691003a258e5e4bd247cde0fbe13
      authorities:
      - '*'
      credentials:
        app_id:
          - header:
              keys:
                - x-jwt-payload
              ops:
                - base64_urlsafe
                - json:
                  - keys:
                    - azp
                    - aud
                - take:
                    head: 1
      mapping_rules:
      - method: GET
        pattern: /
        usages:
        - delta: 1
          name: hits
